#pragma once

enum class EventType {
    SET_SHADER,
    DRAW,
    OBJ_POS_CHANGED,
    SET_SHADER_PROJECTION,
    SET_SHADER_VIEW,
    SET_SHADER_MODEL,
    SET_SHADER_VIEWPOS,
    SET_SHADER_DIR_LIGHTS,
    SET_SHADER_POINT_LIGHTS,
    SET_SHADER_SPOT_LIGHTS,
    SET_SHADER_FLASHLIGHT,
    SET_SHADER_TEXTURE_UNIT,
    CAMERA_CHANGED,
    OBJ_SCALE_CHANGED,
    OBJ_ROTATION_CHANGED
};